"""Component data for the Libra software map (software-map.html).

This is a *proposed* API design derived from the Software architecture section of
LIBRA.md. Firmware is C on ESP-IDF, so a "class" here is a component: a header, an
opaque handle or struct, and a set of lb_* functions. Nothing here is built yet.

Relationship kinds
  uses       a direct call into another component's API (must go to the same or a lower layer)
  notifies   a registered callback upward (the callee registered a handler, the caller invokes it)
"""

LAYERS = ["UI", "Application services", "Core services", "Transports", "Drivers", "Boot and platform"]
UI, APP, CORE, XPORT, DRV, BOOT = range(6)

# layout: (row, col, span) on a 6-column grid; rows are numbered top to bottom
# each component: dict(id, layer, row, col, span, core, purpose, anchor, untrusted, types, funcs,
#                      uses, notifies, ext, notes)


def T(name, kind, desc):
    return (name, kind, desc)


def F(sig, desc):
    return (sig, desc)


COMPONENTS = [
    # ------------------------------------------------------------------ UI
    dict(id="ui", layer=UI, row=0, col=2, span=2, core="1",
         purpose="State machine, screens and the hold-to-confirm engine. Owns presentation only: every approval and every secret is delegated to `session` and the services.",
         anchor="user-interface", untrusted=False,
         types=[
             T("lb_ui_state_t", "enum", "Idle, Locked, ShowQR, Accounts, TOTPCode, Scan, ConfirmOTP, ConfirmExchange, Challenge, HumanCheck, Sign, ReturnCert, ShowText, HostRequest, CardPrompt, VaultPrompt, StickPrompt, Connected, Settings"),
             T("lb_hold_t", "struct", "req_id, required_ms, started_ms, summary_digest. The request is captured when the hold starts; any change to it resets the hold"),
             T("lb_ui_evt_t", "struct", "A tagged event from input, session or media, delivered to the state machine"),
         ],
         funcs=[
             F("lb_err_t lb_ui_init(void)", "Initialise the display, register listeners with input, session, vault and storage"),
             F("void lb_ui_task(void *arg)", "Core 1 loop: render, scan and dispatch events"),
             F("lb_ui_state_t lb_ui_state(void)", "Current state"),
             F("void lb_ui_on_input(const lb_input_evt_t *e)", "Callback from `input`: drives the state machine"),
             F("void lb_ui_on_session(const lb_session_evt_t *e)", "Callback from `session`: lock changed, request pending, unlock needed"),
             F("void lb_ui_on_media(const lb_media_evt_t *e)", "Callback from `vault` and `storage`: card or stick present, state changed"),
             F("lb_err_t lb_ui_hold_begin(lb_req_id_t id, uint32_t ms)", "Start the hold engine for a pending request; haptic ticks while held"),
             F("void lb_ui_hold_cancel(void)", "Release, Back, or the request changed"),
             F("void lb_ui_show_text(const char *title, const char *body)", "ShowText: used to refuse unknown QR payloads"),
             F("void lb_ui_show_recovery_key(const lb_recovery_key_t *k)", "Show the recovery key as Base32 groups and a QR, once"),
         ],
         uses=["session", "oath", "xch", "backup", "vault", "storage", "profile", "time", "qr", "qrparse",
               "camera", "display", "input", "haptic", "fp", "power"],
         notifies=[], ext=["LVGL or a hand-written renderer (undecided)"],
         notes=["Never calls `crypto` or `keystore` directly.",
                "Scan state: camera frame -> `qr` decode -> `qrparse` -> dispatch by type to `oath` or `xch`."]),

    # ------------------------------------------------------------------ APP
    dict(id="oath", layer=APP, row=1, col=0, span=1, core="0 (proposed)",
         purpose="TOTP and HOTP accounts: parse otpauth URIs, store secrets, produce codes.",
         anchor="oath", untrusted=False,
         types=[
             T("lb_oath_type_t", "enum", "TOTP, HOTP"),
             T("lb_oath_alg_t", "enum", "SHA1, SHA256, SHA512"),
             T("lb_oath_entry_t", "struct", "id, issuer, account, type, alg, digits (6 or 8), period or counter, reveal_requires_hold, secret (never leaves)"),
             T("lb_oath_code_t", "struct", "digits string, remaining_s"),
         ],
         funcs=[
             F("lb_err_t lb_oath_from_qr(const lb_qr_msg_t *m, lb_oath_entry_t *out)", "Validated entry for the ConfirmOTP screen; nothing is stored yet"),
             F("lb_err_t lb_oath_add(const lb_oath_entry_t *e)", "Store after approval, through `keystore`"),
             F("lb_err_t lb_oath_add_manual(const char *base32, const lb_oath_entry_t *meta)", "Fallback entry"),
             F("lb_err_t lb_oath_list(lb_oath_summary_t *out, size_t *n)", "Accounts without secrets"),
             F("lb_err_t lb_oath_code(lb_oath_id_t id, lb_oath_code_t *out)", "TOTP refuses if the clock is untrusted. HOTP advances and stores the counter before returning the code"),
             F("lb_err_t lb_oath_reveal_required(lb_oath_id_t id, bool *req)", "Per-account hold-to-reveal setting"),
             F("lb_err_t lb_oath_rename(lb_oath_id_t id, const char *name)", "Management"),
             F("lb_err_t lb_oath_delete(lb_oath_id_t id)", "Management; requires approval"),
             F("lb_err_t lb_oath_type_code(lb_oath_id_t id)", "Optional: type the code as keyboard HID when plugged in"),
             F("lb_err_t lb_oath_ccid_command(const uint8_t *apdu, size_t n, uint8_t *out, size_t *m)", "Optional YubiKey OATH protocol over CCID (verify what the reused firmware offers)"),
         ],
         uses=["keystore", "crypto", "time", "qrparse", "usb"], notifies=[],
         ext=["pico-fido / pico-hsm family (reuse, verify licence and S3 support)"],
         notes=["Secrets are not shown or exported except through the encrypted backup."]),

    dict(id="openpgp", layer=APP, row=1, col=1, span=1, core="0",
         purpose="OpenPGP card applet over CCID. The desktop gpg and scdaemon do decrypt and sign through it; also certifies peer keys for `xch`.",
         anchor="software-architecture", untrusted=True,
         types=[
             T("lb_pgp_slot_t", "enum", "SIG, DEC, AUT"),
             T("lb_pgp_cert_level_t", "enum", "CASUAL (0x12), POSITIVE (0x13) (verify against the OpenPGP spec and GnuPG)"),
             T("lb_pgp_fp_t", "struct", "Key fingerprint"),
         ],
         funcs=[
             F("lb_err_t lb_pgp_init(void)", "Register the CCID handler with `usb`"),
             F("lb_err_t lb_pgp_ccid_apdu(const uint8_t *in, size_t n, uint8_t *out, size_t *m)", "Callback from `usb`: dispatch SELECT, VERIFY (pin-pad), PSO:CDS, PSO:DECIPHER, INTERNAL AUTHENTICATE, GENERATE KEY, GET DATA, PUT DATA"),
             F("lb_err_t lb_pgp_key_generate(lb_pgp_slot_t s, lb_alg_t alg)", "Create a key; also creates its revocation certificate"),
             F("lb_err_t lb_pgp_key_import(lb_pgp_slot_t s, const uint8_t *k, size_t n)", "Import"),
             F("lb_err_t lb_pgp_public_key(lb_pgp_slot_t s, uint8_t *out, size_t *n)", "Export the public key (also used to show my QR)"),
             F("lb_err_t lb_pgp_fingerprint(lb_pgp_slot_t s, lb_pgp_fp_t *out)", "Fingerprint"),
             F("lb_err_t lb_pgp_sign(lb_pgp_slot_t s, const uint8_t *digest, size_t n, uint8_t *sig, size_t *m)", "PSO:CDS; requests approval first, then signs"),
             F("lb_err_t lb_pgp_decipher(lb_pgp_slot_t s, const uint8_t *ct, size_t n, uint8_t *pt, size_t *m)", "PSO:DECIPHER; requests approval first"),
             F("lb_err_t lb_pgp_certify(const uint8_t *peer_pub, size_t n, uint32_t uid_mask, lb_pgp_cert_level_t lvl, uint8_t *cert, size_t *m)", "Certify only the confirmed user IDs; the caller (`xch`) has already obtained approval"),
             F("lb_err_t lb_pgp_revocation_cert(lb_pgp_slot_t s, lb_pgp_reason_t why, uint8_t *out, size_t *n)", "Generated at key creation for printing or the System card"),
         ],
         uses=["keystore", "crypto", "session", "usb"], notifies=[],
         ext=["pico-openpgp (reuse, verify)"],
         notes=["APDU input is untrusted: length-check everything.",
                "While waiting for approval it sends CCID time extension through `usb`."]),

    dict(id="fido", layer=APP, row=1, col=2, span=1, core="0",
         purpose="FIDO2 / CTAP2 and U2F, with resident credentials (SSH sk- keys work).",
         anchor="software-architecture", untrusted=True,
         types=[
             T("lb_fido_cred_t", "struct", "rp_id_hash, user handle, credential id, signature counter, resident flag"),
             T("lb_ctap_status_t", "enum", "OK, PROCESSING, UPNEEDED, error codes"),
         ],
         funcs=[
             F("lb_err_t lb_fido_init(void)", "Register the HID handler with `usb`"),
             F("lb_err_t lb_fido_ctap_message(const uint8_t *in, size_t n, uint8_t *out, size_t *m)", "Callback from `usb`: dispatch CTAP2 and U2F commands"),
             F("lb_err_t lb_fido_get_info(uint8_t *out, size_t *n)", "authenticatorGetInfo"),
             F("lb_err_t lb_fido_make_credential(const lb_ctap_mc_req_t *r, lb_ctap_mc_rsp_t *rsp)", "Requests approval (hold) before creating"),
             F("lb_err_t lb_fido_get_assertion(const lb_ctap_ga_req_t *r, lb_ctap_ga_rsp_t *rsp)", "Requests approval before signing"),
             F("lb_err_t lb_fido_list_resident(lb_fido_cred_t *out, size_t *n)", "Credential management"),
             F("lb_err_t lb_fido_delete_resident(const uint8_t *cred_id, size_t n)", "Requires approval"),
             F("lb_err_t lb_fido_reset(void)", "Requires approval; wipes credentials"),
         ],
         uses=["keystore", "crypto", "session", "usb"], notifies=[],
         ext=["pico-fido (reuse, verify)"],
         notes=["Sends CTAP keep-alive through `usb` while waiting for approval.",
                "Resident credentials are not in the v0 backup (a later decision)."]),

    dict(id="xch", layer=APP, row=1, col=3, span=1, core="1 (proposed)",
         purpose="The key-signing dance: proof of key possession, human confirmation, signing and certificate return.",
         anchor="key-exchange", untrusted=True,
         types=[
             T("lb_xch_state_t", "enum", "IDLE, SCANNED, EXCHANGING, PROVEN, CONFIRM, APPROVED, SIGNED, RETURNED"),
             T("lb_xch_peer_t", "struct", "fingerprint, nonce, ble_addr, user IDs (shown for confirmation), chosen level"),
             T("lb_xch_msg_t", "enum", "KEY, PROOF, CERT (carried over BLE)"),
         ],
         funcs=[
             F("lb_err_t lb_xch_show_my_qr(lb_qr_matrix_t *out)", "Build my QR: fingerprint, nonce, BLE address"),
             F("lb_err_t lb_xch_on_peer_qr(const lb_qr_msg_t *m)", "Start a session from a scanned peer QR; opens BLE"),
             F("void lb_xch_on_ble_rx(const uint8_t *buf, size_t n)", "Callback from `ble`: receive the key, the proof, then the certificate"),
             F("lb_err_t lb_xch_peer_uids(lb_xch_uid_t *out, size_t *n)", "Names and fingerprint for the HumanCheck screen"),
             F("lb_err_t lb_xch_set_confirmed(uint32_t uid_mask, lb_pgp_cert_level_t lvl)", "The person's answer; only confirmed names are ever signed"),
             F("lb_err_t lb_xch_sign_confirmed(void)", "After approval: certify through `openpgp`"),
             F("lb_err_t lb_xch_return_cert(void)", "Send my certification of the peer over BLE; keep the received one"),
             F("lb_err_t lb_xch_met_log_append(const lb_xch_peer_t *p)", "Write to the met log on the System card"),
             F("void lb_xch_abort(lb_xch_reason_t why)", "Cancel, timeout or Back; close BLE"),
         ],
         uses=["openpgp", "crypto", "session", "qr", "qrparse", "ble", "storage", "time"], notifies=[],
         ext=[],
         notes=["Every signed message carries a domain-separation string, both fingerprints and the peer's fresh nonce.",
                "Fallback path puts the key in the QR and uses extra QR rounds (no BLE)."]),

    dict(id="backup", layer=APP, row=1, col=4, span=1, core="0 (proposed)",
         purpose="Encrypted export and import using a random recovery key. v0 baseline only; guardian shares are v1.",
         anchor="backup", untrusted=False,
         types=[
             T("lb_recovery_key_t", "struct", "About 130 bits; shown once, never stored on the device"),
             T("lb_backup_hdr_t", "struct", "Format version, key-check data, nonce; the file is authenticated"),
         ],
         funcs=[
             F("lb_err_t lb_backup_create(lb_recovery_key_t *key_out)", "Generate the recovery key, export wrapped secrets, seal with AEAD, write to the System card"),
             F("lb_err_t lb_backup_restore(const lb_recovery_key_t *key)", "Confirm before overwriting, then import"),
             F("bool lb_backup_is_stale(void)", "True when the keystore generation has moved since the last backup"),
             F("uint16_t lb_backup_format_version(void)", "Versioned in spec/"),
         ],
         uses=["keystore", "crypto", "storage", "session"], notifies=[],
         ext=[],
         notes=["Includes: OpenPGP keys, OATH secrets and counters, the wrapped Vault volume key, settings.",
                "Excludes: fingerprint templates, the Vault card's data, FIDO resident credentials (v0).",
                "Restoring an old backup restores old HOTP counters; the UI warns."]),

    # ------------------------------------------------------------------ CORE
    dict(id="session", layer=CORE, row=2, col=0, span=1, core="0 (proposed)",
         purpose="Owns the two gates: unlock (the combo) and approval (a PTT hold with a fingerprint). Lock state, unlock policy, pending host requests.",
         anchor="session-policy", untrusted=False,
         types=[
             T("lb_lock_state_t", "enum", "LOCKED, UNLOCKED"),
             T("lb_unlock_result_t", "struct", "outcome {OK, BAD, DELAYED, WIPED}, delay_ms, attempts_left"),
             T("lb_req_t", "struct", "origin (USB or UI), kind (SIGN, DECRYPT, AUTH, OATH_REVEAL, VAULT, STICK, XCH_SIGN, BACKUP, RESTORE), summary, hold_ms"),
             T("lb_policy_t", "struct", "combo_min 8, combo_max 16, bad_limit 10, idle_ms 60000"),
             T("lb_session_evt_t", "struct", "LOCK_CHANGED, REQUEST_PENDING, UNLOCK_NEEDED, REQUEST_DONE"),
         ],
         funcs=[
             F("lb_err_t lb_session_init(void)", "Load policy; start locked"),
             F("lb_lock_state_t lb_session_state(void)", "Current lock state"),
             F("lb_err_t lb_session_unlock(const uint8_t *combo, size_t n, lb_unlock_result_t *out)", "The attempt counter is written before the check; delays 0, 0, 0, 5 s, 30 s, 5 min; wipe at the limit"),
             F("void lb_session_lock(lb_lock_reason_t why)", "Idle, Back (long), unplug or power-up; zeroizes keys"),
             F("void lb_session_activity(void)", "Reset the idle timer (called on any input)"),
             F("lb_err_t lb_session_request(const lb_req_t *r, lb_req_id_t *id)", "Register something that needs approval. If locked, keep it pending up to about 30 s and notify the UI to ask for unlock"),
             F("lb_err_t lb_session_hold_complete(lb_req_id_t id)", "The UI reports the hold finished; session then asks `fp` for a match (combo is the fallback)"),
             F("lb_err_t lb_session_await(lb_req_id_t id, uint32_t timeout_ms, lb_decision_t *out)", "A protocol task blocks (while `usb` sends keep-alive) until approved, denied or expired"),
             F("void lb_session_cancel(lb_req_id_t id)", "Back, or a new request replaces the pending one"),
             F("void lb_session_set_listener(const lb_session_listener_t *l)", "The UI registers for events (no upward calls)"),
             F("const lb_policy_t *lb_session_policy(void)", "Read the policy"),
             F("lb_err_t lb_session_set_policy(const lb_policy_t *p)", "Validated: combo length and limits stay in range"),
         ],
         uses=["keystore", "fp"], notifies=["ui"],
         ext=["esp_timer (idle timer)"],
         notes=["Only one approval is pending at a time; a new host request cancels the old one.",
                "Fingerprint is a convenience factor and never releases keys alone."]),

    dict(id="keystore", layer=CORE, row=2, col=1, span=1, core="0",
         purpose="Encrypted storage for keys, OTP secrets and counters; PIN KDF; persistent retry counter; wipe.",
         anchor="security", untrusted=False,
         types=[
             T("lb_secret_kind_t", "enum", "OPENPGP_KEY, OATH_SECRET, FIDO_CRED, VAULT_VOLUME_KEY, SETTINGS_SECRET"),
             T("lb_ks_id_t", "struct", "kind and index"),
             T("lb_kdf_params_t", "struct", "Argon2id memory, iterations, lanes, salt (stored beside the verifier)"),
         ],
         funcs=[
             F("lb_err_t lb_ks_init(void)", "Open the encrypted secrets partition"),
             F("lb_err_t lb_ks_provision(const uint8_t *combo, size_t n)", "First run: create the verifier, salt and parameters"),
             F("lb_err_t lb_ks_attempt_begin(uint8_t *count)", "Persist the attempt counter (journalled) before a check"),
             F("lb_err_t lb_ks_unlock(const uint8_t *combo, size_t n)", "Derive the wrapping key with Argon2id (about 1 s) and verify"),
             F("lb_err_t lb_ks_attempt_end(bool ok)", "Reset the counter on success"),
             F("void lb_ks_lock(void)", "Zeroize the wrapping key and cached secrets"),
             F("bool lb_ks_is_unlocked(void)", "State"),
             F("lb_err_t lb_ks_put(lb_ks_id_t id, const uint8_t *blob, size_t n)", "Store; bumps the generation"),
             F("lb_err_t lb_ks_get(lb_ks_id_t id, uint8_t *out, size_t *n)", "Requires unlocked"),
             F("lb_err_t lb_ks_delete(lb_ks_id_t id)", "Remove; bumps the generation"),
             F("lb_err_t lb_ks_list(lb_secret_kind_t k, lb_ks_id_t *ids, size_t *n)", "Enumerate"),
             F("lb_err_t lb_ks_counter_advance(lb_ks_id_t id, uint64_t *new_value)", "HOTP and signature counters: persisted before returning"),
             F("uint32_t lb_ks_generation(void)", "Monotonic change counter; the backup uses it for staleness"),
             F("lb_err_t lb_ks_export_wrapped(uint8_t *out, size_t *n)", "For the backup"),
             F("lb_err_t lb_ks_import(const uint8_t *in, size_t n)", "Restore"),
             F("void lb_ks_wipe(void)", "Destroy the wrapped keys; the Vault becomes unreadable"),
         ],
         uses=["crypto", "profile"], notifies=[],
         ext=["esp_partition, NVS or a custom journal (open: counter storage)", "flash encryption at L2"],
         notes=["At L1 the device-unique secret sits in ordinary flash, so offline guessing is possible after a dump.",
                "Counter writes must survive a power cut and respect a flash write budget (verify endurance)."]),

    dict(id="crypto", layer=CORE, row=2, col=2, span=1, core="0",
         purpose="Signing, key agreement, hashing, AEAD, the Argon2id KDF and AES-XTS, with measured timings for profile alerts. Uses the secure element when fitted.",
         anchor="crypto-profiles", untrusted=False,
         types=[
             T("lb_alg_t", "enum", "ED25519, X25519, P256, RSA2048, RSA3072, RSA4096"),
             T("lb_hash_t", "enum", "SHA1, SHA256, SHA512"),
             T("lb_xts_ctx_t", "struct", "AES-256-XTS context (two 256-bit keys)"),
             T("lb_alert_t", "struct", "alg, measured sign time (ms), hardware-limit warning text"),
         ],
         funcs=[
             F("void lb_crypto_random(uint8_t *buf, size_t n)", "Hardware RNG (valid only under the right conditions; verify)"),
             F("lb_err_t lb_crypto_keygen(lb_alg_t a, uint8_t *priv, size_t *pn, uint8_t *pub, size_t *un)", "Generate a keypair"),
             F("lb_err_t lb_crypto_sign(lb_alg_t a, const uint8_t *priv, const uint8_t *msg, size_t n, uint8_t *sig, size_t *m)", "Sign (RSA uses the accelerator)"),
             F("lb_err_t lb_crypto_verify(lb_alg_t a, const uint8_t *pub, const uint8_t *msg, size_t n, const uint8_t *sig, size_t m)", "Verify"),
             F("lb_err_t lb_crypto_ecdh(lb_alg_t a, const uint8_t *priv, const uint8_t *peer, uint8_t *secret)", "Key agreement"),
             F("lb_err_t lb_crypto_rsa_decrypt(const uint8_t *priv, const uint8_t *ct, size_t n, uint8_t *pt, size_t *m)", "RSA decrypt"),
             F("lb_err_t lb_crypto_hash(lb_hash_t h, const uint8_t *in, size_t n, uint8_t *out)", "Hash"),
             F("lb_err_t lb_crypto_hmac(lb_hash_t h, const uint8_t *key, size_t kn, const uint8_t *msg, size_t n, uint8_t *out)", "Used for TOTP and HOTP"),
             F("lb_err_t lb_crypto_aead_seal(const uint8_t *key, const uint8_t *nonce, const uint8_t *aad, size_t an, const uint8_t *in, size_t n, uint8_t *out)", "AES-256-GCM"),
             F("lb_err_t lb_crypto_aead_open(const uint8_t *key, const uint8_t *nonce, const uint8_t *aad, size_t an, const uint8_t *in, size_t n, uint8_t *out)", "Authenticated decrypt"),
             F("lb_err_t lb_crypto_kdf_argon2id(const uint8_t *secret, size_t n, const lb_kdf_params_t *p, uint8_t *key)", "Runs in its own lower-priority task (about 1 s)"),
             F("lb_err_t lb_crypto_xts_init(lb_xts_ctx_t *c, const uint8_t key[64])", "Vault block cipher setup"),
             F("lb_err_t lb_crypto_xts_crypt(lb_xts_ctx_t *c, bool enc, uint64_t sector, const uint8_t *in, uint8_t *out, size_t n)", "Sector number is the tweak; no integrity"),
             F("lb_err_t lb_crypto_alert(lb_alg_t a, lb_alert_t *out)", "Measured time and the hardware-limit warning for the UI"),
             F("uint32_t lb_crypto_bench(lb_alg_t a)", "Benchmark and cache"),
         ],
         uses=["profile", "se"], notifies=[],
         ext=["mbedTLS", "ESP32-S3 RSA, AES, SHA, HMAC and DS peripherals", "Argon2 reference implementation (verify)", "Ed25519 implementation (verify)"],
         notes=["Dispatch to the secure element when `profile` reports one (call goes through `lb_se_*` inside the component).",
                "All secret buffers are zeroized after use."]),

    dict(id="profile", layer=CORE, row=2, col=3, span=1, core="any",
         purpose="Detect the secure element, fuses and RAM and compute the protection level L0 to L3. Never over-claims.",
         anchor="protection-levels", untrusted=False,
         types=[
             T("lb_level_t", "enum", "L0, L1, L2, L3"),
             T("lb_profile_t", "struct", "level, se_present, psram_bytes, flash_encryption, secure_boot, ds_available"),
         ],
         funcs=[
             F("void lb_profile_detect(void)", "At boot: read `boot` state and probe the secure element"),
             F("const lb_profile_t *lb_profile_get(void)", "Current profile"),
             F("const char *lb_level_badge(lb_level_t l)", "Text for the UI badge, including the dev-mode banner at L0 and L1"),
             F("bool lb_profile_has_se(void)", "Whether the secure element is fitted"),
         ],
         uses=["boot", "se"], notifies=[], ext=[],
         notes=["v0 reports L0 or L1 only (no eFuses)."]),

    dict(id="time", layer=CORE, row=2, col=4, span=1, core="any",
         purpose="Clock: read and set, host sync, and trust state. TOTP is refused when the clock is untrusted.",
         anchor="oath", untrusted=False,
         types=[T("lb_time_trust_t", "enum", "UNSET, STALE, TRUSTED")],
         funcs=[
             F("uint64_t lb_time_now(void)", "Unix time from the RTC"),
             F("lb_err_t lb_time_set(uint64_t unix, lb_time_src_t src)", "From the UI (manual) or the host tool"),
             F("lb_time_trust_t lb_time_trust(void)", "Trust state"),
             F("uint32_t lb_time_age_s(void)", "Seconds since the last sync"),
             F("bool lb_time_totp_allowed(void)", "False when the clock is untrusted"),
         ],
         uses=["rtc"], notifies=[], ext=[], notes=[]),

    dict(id="qrparse", layer=CORE, row=2, col=5, span=1, core="any",
         purpose="Strict allow-list parser for QR payloads. A pure function with no I/O. The main attack surface for scanned input.",
         anchor="key-exchange-rules", untrusted=True,
         types=[
             T("lb_qr_type_t", "enum", "OTPAUTH, PEER_FP, PEER_KEY, RECOVERY_KEY, UNKNOWN"),
             T("lb_qr_msg_t", "struct", "Tagged union of parsed fields with fixed maximum sizes"),
         ],
         funcs=[
             F("lb_err_t lb_qrparse(const uint8_t *payload, size_t n, lb_qr_msg_t *out)", "Header (version, type, length, CRC), then an allow-list by type; anything unknown is rejected"),
             F("const lb_qr_limits_t *lb_qrparse_limits(void)", "Hard limits on size and field counts"),
         ],
         uses=[], notifies=[], ext=[],
         notes=["No recursion and no allocation driven by untrusted lengths.", "Fuzz it on the host."]),

    dict(id="storage", layer=CORE, row=3, col=0, span=1, core="any",
         purpose="System card: mount, card detect and minimal sandboxed FAT access with fixed filenames and size limits.",
         anchor="software-architecture", untrusted=True,
         types=[T("lb_sys_file_t", "enum", "MET_LOG, BACKUP, CONTACTS, SETTINGS_EXPORT")],
         funcs=[
             F("lb_err_t lb_sys_mount(void)", "Power the slot and mount"),
             F("void lb_sys_unmount(void)", "Unmount and power off"),
             F("bool lb_sys_present(void)", "Card detect"),
             F("lb_err_t lb_sys_read(lb_sys_file_t f, uint8_t *buf, size_t max, size_t *n)", "Fixed names only; hard size cap"),
             F("lb_err_t lb_sys_write(lb_sys_file_t f, const uint8_t *buf, size_t n)", "Fixed names only"),
             F("size_t lb_sys_free_bytes(void)", "Free space"),
             F("void lb_sys_set_listener(lb_media_cb_t cb)", "The UI registers for insert and remove events"),
         ],
         uses=["sdcard"], notifies=["ui"], ext=["FATFS (restricted use)"],
         notes=["The card is untrusted input: fuzz it like `qrparse`."]),

    dict(id="vault", layer=CORE, row=3, col=1, span=1, core="0",
         purpose="Block encryption broker: AES-256-XTS between the USB mass-storage class and an SD card or a plugged-in stick. Never parses the filesystem.",
         anchor="vault-data-path", untrusted=False,
         types=[
             T("lb_media_t", "enum", "SD, STICK"),
             T("lb_vault_state_t", "enum", "ABSENT, LOCKED, UNLOCKED, CONNECTED"),
             T("lb_media_ops_t", "struct", "present, capacity, read, write: one implementation each for `sdcard` and `usbhost`"),
             T("lb_media_evt_t", "struct", "media, kind (PRESENT, REMOVED, STATE)"),
         ],
         funcs=[
             F("lb_err_t lb_vault_init(void)", "Register media listeners and the MSC handlers"),
             F("lb_vault_state_t lb_vault_state(lb_media_t m)", "State per medium"),
             F("lb_err_t lb_vault_provision(lb_media_t m)", "Write header sectors and the wrapped key. Destructive: needs approval, and a plain stick is never silently erased"),
             F("lb_err_t lb_vault_unlock(lb_media_t m)", "Fetch the volume key from `keystore` after the fingerprint unlock; set up XTS"),
             F("lb_err_t lb_vault_connect(lb_media_t m)", "After the PTT hold: expose the drive to the host"),
             F("void lb_vault_lock(void)", "On unplug, Back or timeout: zeroize the volume key; report media not present"),
             F("lb_err_t lb_vault_set_readonly(bool ro)", "Firmware rejects writes when set"),
             F("size_t lb_vault_capacity(lb_media_t m)", "Medium minus the header sectors"),
             F("lb_err_t lb_vault_msc_read(uint32_t lba, uint32_t n, uint8_t *buf)", "Callback from `usb`: read, decrypt, hand to the host"),
             F("lb_err_t lb_vault_msc_write(uint32_t lba, uint32_t n, const uint8_t *buf)", "Callback from `usb`: encrypt, write"),
             F("void lb_vault_on_media(lb_media_t m, bool present)", "Callback from `sdcard` and `usbhost`"),
             F("void lb_vault_set_listener(lb_media_cb_t cb)", "The UI registers for state changes"),
         ],
         uses=["keystore", "crypto", "session", "usb", "sdcard", "usbhost"], notifies=["ui"],
         ext=[],
         notes=["Runs on core 0 with the USB stack so the UI stays responsive.",
                "Stick: powered on insertion but not enumerated until the fingerprint unlock."]),

    # ------------------------------------------------------------------ XPORT
    dict(id="usb", layer=XPORT, row=4, col=0, span=1, core="0",
         purpose="USB composite device: CCID, FIDO HID, keyboard HID and mass storage. Routes host traffic up to the handlers registered by the services.",
         anchor="second-usb-port", untrusted=True,
         types=[
             T("lb_ccid_handler_t", "callback", "Receives an APDU, returns a response; registered by `openpgp`"),
             T("lb_ctap_handler_t", "callback", "Receives a CTAP frame; registered by `fido`"),
             T("lb_msc_ops_t", "struct", "read, write, capacity, ready; registered by `vault`"),
         ],
         funcs=[
             F("lb_err_t lb_usb_init(void)", "Start TinyUSB with the composite descriptor (check the endpoint budget in a build)"),
             F("bool lb_usb_connected(void)", "Host present"),
             F("void lb_usb_ccid_set_handler(lb_ccid_handler_t h)", "Register"),
             F("lb_err_t lb_usb_ccid_send(const uint8_t *buf, size_t n)", "Respond"),
             F("void lb_usb_ccid_time_extension(void)", "Tell the host to keep waiting for approval"),
             F("void lb_usb_ctap_set_handler(lb_ctap_handler_t h)", "Register"),
             F("lb_err_t lb_usb_ctap_send(const uint8_t *buf, size_t n)", "Respond"),
             F("void lb_usb_ctap_keepalive(lb_ctap_status_t s)", "CTAP keep-alive while waiting"),
             F("lb_err_t lb_usb_kbd_type(const char *s)", "Optional OTP keystroke output"),
             F("void lb_usb_msc_set_handler(const lb_msc_ops_t *ops)", "Register"),
             F("void lb_usb_msc_set_ready(bool ready)", "Media present or not (a locked Vault says not present)"),
         ],
         uses=["power"], notifies=["openpgp", "fido", "vault"],
         ext=["TinyUSB"],
         notes=["Host traffic is untrusted.", "Open: how the host tool (time sync, backup, update) reaches the device; no interface for it is defined yet."]),

    dict(id="ble", layer=XPORT, row=4, col=1, span=1, core="1",
         purpose="BLE for bulk transfer: key exchange and companion pairing. Off by default; on only when asked for.",
         anchor="message-flow", untrusted=True,
         types=[T("lb_ble_state_t", "enum", "OFF, ADVERTISING, CONNECTED")],
         funcs=[
             F("lb_err_t lb_ble_enable(uint32_t window_ms)", "On for a bounded window, then off"),
             F("void lb_ble_disable(void)", "Off"),
             F("lb_err_t lb_ble_connect(const uint8_t *addr, const uint8_t *expected_fp)", "Connect and authenticate against the scanned fingerprint"),
             F("lb_err_t lb_ble_send(const uint8_t *buf, size_t n)", "Send"),
             F("void lb_ble_set_rx_cb(lb_ble_rx_t cb)", "Register the receiver (`xch`)"),
             F("lb_err_t lb_ble_pair_numeric(uint32_t *code)", "Companion pairing with a numeric comparison"),
             F("lb_ble_state_t lb_ble_state(void)", "State"),
         ],
         uses=[], notifies=["xch"], ext=["NimBLE or Bluedroid (verify)"],
         notes=["LE Secure Connections with numeric comparison (verify against the stack)."]),

    dict(id="qr", layer=XPORT, row=4, col=2, span=1, core="1",
         purpose="QR encode (show my key, show the recovery key) and decode (quirc-style, on a grayscale frame in PSRAM).",
         anchor="qr-feasibility", untrusted=True,
         types=[T("lb_qr_matrix_t", "struct", "Module matrix, version, side")],
         funcs=[
             F("lb_err_t lb_qr_encode(const uint8_t *payload, size_t n, lb_qr_ecc_t ecc, lb_qr_matrix_t *out)", "Encode; ECC level L or M"),
             F("void lb_qr_render(const lb_qr_matrix_t *m, uint16_t *buf, uint8_t px_per_module)", "Draw for the display"),
             F("lb_err_t lb_qr_decode(const lb_frame_t *f, uint8_t *out, size_t *n)", "Decode the first code in the frame"),
         ],
         uses=[], notifies=[], ext=["quirc (verify)", "QR encoder library (verify)"],
         notes=["A fingerprint QR is about 100 bytes (v5); a whole key about 300 bytes (v11, marginal on small screens)."]),

    # ------------------------------------------------------------------ DRV
    dict(id="display", layer=DRV, row=5, col=0, span=1, core="n/a",
         purpose="SPI display driver.", anchor="electrical", untrusted=False,
         types=[],
         funcs=[
             F("lb_err_t lb_disp_init(void)", "Init the panel"),
             F("void lb_disp_blit(uint16_t x, uint16_t y, uint16_t w, uint16_t h, const uint16_t *px)", "Draw a rectangle"),
             F("void lb_disp_fill(uint16_t color)", "Clear"),
             F("void lb_disp_set_backlight(uint8_t pct)", "Dim in menus, off when idle"),
             F("void lb_disp_sleep(bool on)", "Panel sleep"),
         ],
         uses=[], notifies=[], ext=["esp_lcd, SPI master"], notes=["Shares the SPI bus with the SD cards."]),

    dict(id="input", layer=DRV, row=5, col=1, span=1, core="1",
         purpose="Button scan through the two I/O expanders and the direct PTT pin, with debounce and PTT tap or hold timing.",
         anchor="electrical", untrusted=False,
         types=[
             T("lb_button_t", "enum", "UP, DOWN, LEFT, RIGHT, SELECT, BACK, PTT"),
             T("lb_input_evt_t", "struct", "button, kind {PRESS, RELEASE, TAP, HOLD_START, HOLD_DONE}, t_ms"),
         ],
         funcs=[
             F("lb_err_t lb_input_init(void)", "Configure the expanders and the interrupt line"),
             F("void lb_input_set_listener(lb_input_cb_t cb)", "The UI registers for events"),
             F("bool lb_input_is_down(lb_button_t b)", "Raw state"),
             F("void lb_input_set_hold_ms(uint32_t ms)", "Hold threshold (about 0.5 s login, 1.5 s signing or deleting)"),
         ],
         uses=[], notifies=["ui"], ext=["I2C master"], notes=["Wakes the MCU through the expander interrupt."]),

    dict(id="camera", layer=DRV, row=5, col=2, span=1, core="1",
         purpose="Camera over the parallel interface: grayscale frames into PSRAM.", anchor="camera-options", untrusted=False,
         types=[T("lb_frame_t", "struct", "width, height, stride, gray pixels (PSRAM), length")],
         funcs=[
             F("lb_err_t lb_cam_init(lb_cam_mode_t m)", "QVGA or VGA"),
             F("lb_err_t lb_cam_capture_gray(lb_frame_t *f)", "Capture a frame"),
             F("void lb_cam_release(lb_frame_t *f)", "Free the frame buffer"),
             F("void lb_cam_set_mode(lb_cam_mode_t m)", "Resolution"),
             F("void lb_cam_power(bool on)", "Through `power`"),
         ],
         uses=["power"], notifies=[], ext=["esp_camera or the LCD_CAM driver"], notes=[]),

    dict(id="fp", layer=DRV, row=5, col=3, span=1, core="1",
         purpose="Fingerprint module over UART: enrol, match, wake. A convenience factor; the link itself is unauthenticated.",
         anchor="fingerprint", untrusted=False,
         types=[T("lb_fp_result_t", "struct", "matched, slot, score")],
         funcs=[
             F("lb_err_t lb_fp_init(void)", "UART setup"),
             F("lb_err_t lb_fp_enrol(uint8_t slot, lb_fp_progress_t cb)", "Enrol with progress callbacks"),
             F("lb_err_t lb_fp_match(uint32_t timeout_ms, lb_fp_result_t *out)", "Wait for a finger and match"),
             F("lb_err_t lb_fp_delete(uint8_t slot)", "Remove a template"),
             F("uint8_t lb_fp_count(void)", "Enrolled fingers"),
             F("void lb_fp_power(bool on)", "Main supply; the touch IRQ rail stays on"),
             F("void lb_fp_wake_enable(bool on)", "Wake on touch"),
         ],
         uses=["power"], notifies=[], ext=["UART"], notes=["Templates stay on the sensor module."]),

    dict(id="haptic", layer=DRV, row=5, col=4, span=1, core="n/a",
         purpose="Vibration motor and piezo for acknowledgement and hold progress.", anchor="electrical", untrusted=False,
         types=[T("lb_haptic_t", "enum", "TAP_ACK, HOLD_TICK, HOLD_DONE, DENY")],
         funcs=[
             F("void lb_haptic_pulse(lb_haptic_t p)", "Play a pattern"),
             F("void lb_haptic_beep(uint16_t hz, uint16_t ms)", "Piezo"),
         ],
         uses=[], notifies=[], ext=["LEDC or GPIO"], notes=[]),

    dict(id="rtc", layer=DRV, row=5, col=5, span=1, core="n/a",
         purpose="Battery-backed real-time clock.", anchor="electrical", untrusted=False,
         types=[],
         funcs=[
             F("lb_err_t lb_rtc_get(uint64_t *unix)", "Read"),
             F("lb_err_t lb_rtc_set(uint64_t unix)", "Write"),
             F("bool lb_rtc_battery_ok(void)", "Backup cell state"),
         ],
         uses=[], notifies=[], ext=["I2C master"], notes=[]),

    dict(id="power", layer=DRV, row=6, col=0, span=1, core="n/a",
         purpose="Rails, sleep and wake sources, USB power detect and battery (v1).", anchor="power-tree", untrusted=False,
         types=[
             T("lb_rail_t", "enum", "CAMERA, FP, SD_SYSTEM, SD_VAULT, STICK, BACKLIGHT"),
             T("lb_wake_t", "bitmask", "PTT, EXPANDER_INT, FP_IRQ, USB_VBUS"),
         ],
         funcs=[
             F("void lb_power_rail(lb_rail_t r, bool on)", "Switch a rail"),
             F("void lb_power_sleep(lb_wake_t wake_mask)", "Deep sleep"),
             F("lb_wake_t lb_power_wake_cause(void)", "Why we woke"),
             F("bool lb_power_vbus_present(void)", "USB power detect"),
             F("lb_err_t lb_power_battery(uint16_t *mv, uint8_t *pct)", "Battery gauge (v1)"),
         ],
         uses=[], notifies=[], ext=["esp_sleep"], notes=[]),

    dict(id="se", layer=DRV, row=6, col=1, span=1, core="n/a",
         purpose="Optional secure element (not fitted in v0). Keeps keys and a PIN counter in hardware at L3.", anchor="security", untrusted=False,
         types=[],
         funcs=[
             F("bool lb_se_present(void)", "Probe"),
             F("lb_err_t lb_se_keygen(uint8_t slot, lb_alg_t a, uint8_t *pub, size_t *n)", "Generate inside the element"),
             F("lb_err_t lb_se_sign(uint8_t slot, const uint8_t *msg, size_t n, uint8_t *sig, size_t *m)", "Sign inside the element"),
             F("lb_err_t lb_se_ecdh(uint8_t slot, const uint8_t *peer, uint8_t *secret)", "Agree"),
         ],
         uses=[], notifies=[], ext=["I2C master", "vendor library (undecided)"], notes=["The part is undecided; see the Security architecture section."]),

    dict(id="sdcard", layer=DRV, row=6, col=2, span=1, core="n/a",
         purpose="Two microSD slots in SPI mode on the shared bus: per-slot power, detect and block read and write.", anchor="electrical", untrusted=False,
         types=[T("lb_slot_t", "enum", "SYSTEM, VAULT")],
         funcs=[
             F("lb_err_t lb_sd_init(lb_slot_t s)", "Init the slot"),
             F("bool lb_sd_present(lb_slot_t s)", "Card detect"),
             F("void lb_sd_power(lb_slot_t s, bool on)", "Per-slot power through `power`"),
             F("lb_err_t lb_sd_capacity(lb_slot_t s, uint64_t *blocks)", "Size in 512-byte blocks"),
             F("lb_err_t lb_sd_read(lb_slot_t s, uint32_t lba, uint32_t n, uint8_t *buf)", "Read blocks (bus mutex)"),
             F("lb_err_t lb_sd_write(lb_slot_t s, uint32_t lba, uint32_t n, const uint8_t *buf)", "Write blocks"),
             F("void lb_sd_set_listener(lb_sd_cb_t cb)", "`storage` and `vault` register for insert and remove"),
         ],
         uses=["power"], notifies=["vault", "storage"], ext=["SPI master, sdspi"], notes=["Chip selects are separate; the SPI bus is shared with the display."]),

    dict(id="usbhost", layer=DRV, row=6, col=3, span=1, core="n/a",
         purpose="USB host chip for the brokered stick port (tier 1). Block access to a plugged-in stick.", anchor="second-usb-port", untrusted=True,
         types=[],
         funcs=[
             F("lb_err_t lb_usbh_init(void)", "Init the host chip"),
             F("void lb_usbh_power(bool on)", "Stick power: on at insertion"),
             F("void lb_usbh_enumerate(bool on)", "Enumerate only after the fingerprint unlock"),
             F("bool lb_usbh_stick_present(void)", "Detect"),
             F("lb_err_t lb_usbh_capacity(uint64_t *blocks)", "Size"),
             F("lb_err_t lb_usbh_read(uint32_t lba, uint32_t n, uint8_t *buf)", "Read blocks"),
             F("lb_err_t lb_usbh_write(uint32_t lba, uint32_t n, const uint8_t *buf)", "Write blocks"),
             F("void lb_usbh_set_listener(lb_usbh_cb_t cb)", "`vault` registers for detect"),
         ],
         uses=["power"], notifies=["vault"], ext=["MAX3421E host driver with TinyUSB (biggest risk; verify)"],
         notes=["A stick is untrusted hardware: the device never parses its filesystem."]),

    # ------------------------------------------------------------------ BOOT
    dict(id="boot", layer=BOOT, row=7, col=0, span=1, core="n/a",
         purpose="Bootloader, secure boot, flash-encryption state, anti-rollback and OTA slots.", anchor="storage-layout", untrusted=False,
         types=[T("lb_boot_state_t", "struct", "secure_boot, flash_encryption, ds_burned, rollback_index, running_slot")],
         funcs=[
             F("void lb_boot_get_state(lb_boot_state_t *out)", "Read the fuse and OTA state; never over-claims"),
             F("lb_err_t lb_boot_mark_app_valid(void)", "Confirm a new image after the self-test"),
             F("lb_err_t lb_boot_set_next_slot(uint8_t slot)", "Switch the A/B slot after a signed update"),
             F("uint32_t lb_boot_rollback_index(void)", "Anti-rollback counter"),
         ],
         uses=[], notifies=[], ext=["ESP-IDF bootloader, esp_efuse, esp_ota_ops"],
         notes=["Burning eFuses is irreversible and only done in a documented release process."]),
]

# Call flows: (caller, callee, function, note). The caller to callee transition must be a
# declared `uses` or `notifies` relationship, and the function must exist on the callee.
FLOWS = [
    dict(id="unlock", title="Unlock with the combo", steps=[
        ("input", "ui", "lb_ui_on_input", "D-pad presses arrive as events"),
        ("ui", "session", "lb_session_unlock", "The UI hands over the finished combo"),
        ("session", "keystore", "lb_ks_attempt_begin", "The counter is written before the check"),
        ("session", "keystore", "lb_ks_unlock", "Derive and verify"),
        ("keystore", "crypto", "lb_crypto_kdf_argon2id", "About 1 s, in its own task"),
        ("session", "keystore", "lb_ks_attempt_end", "Reset the counter on success"),
        ("session", "ui", "lb_ui_on_session", "Lock state changed (or a delay, or a wipe)"),
        ("session", "keystore", "lb_ks_wipe", "Only at the 10th failure"),
    ]),
    dict(id="oath", title="Enrol an OTP account", steps=[
        ("ui", "camera", "lb_cam_capture_gray", "Scan state"),
        ("ui", "qr", "lb_qr_decode", "Grayscale frame in PSRAM"),
        ("ui", "qrparse", "lb_qrparse", "Allow-list parse; unknown goes to ShowText"),
        ("ui", "oath", "lb_oath_from_qr", "Build the ConfirmOTP entry"),
        ("ui", "session", "lb_session_request", "Ask for approval of the add"),
        ("ui", "session", "lb_session_hold_complete", "PTT hold finished"),
        ("session", "fp", "lb_fp_match", "Fingerprint (combo is the fallback)"),
        ("ui", "oath", "lb_oath_add", "After approval"),
        ("oath", "keystore", "lb_ks_put", "Encrypted storage; generation bumps, so the backup is stale"),
    ]),
    dict(id="sign", title="Host asks to sign (GPG)", steps=[
        ("usb", "openpgp", "lb_pgp_ccid_apdu", "PSO:CDS arrives over CCID"),
        ("openpgp", "session", "lb_session_request", "Request captured; if locked, the UI asks for unlock first"),
        ("session", "ui", "lb_ui_on_session", "HostRequest screen"),
        ("openpgp", "usb", "lb_usb_ccid_time_extension", "Keep the host waiting"),
        ("ui", "session", "lb_session_hold_complete", "Hold with a fingerprint"),
        ("session", "fp", "lb_fp_match", "Approval gate"),
        ("openpgp", "session", "lb_session_await", "Returns approved"),
        ("openpgp", "keystore", "lb_ks_get", "Load the private key"),
        ("openpgp", "crypto", "lb_crypto_sign", "Sign the digest"),
        ("openpgp", "usb", "lb_usb_ccid_send", "APDU response"),
    ]),
    dict(id="xch", title="Sign a peer's key", steps=[
        ("ui", "qr", "lb_qr_decode", "Scan the peer's QR (after the camera capture)"),
        ("ui", "qrparse", "lb_qrparse", "PEER_FP: fingerprint, nonce, BLE address"),
        ("ui", "xch", "lb_xch_on_peer_qr", "Start the exchange"),
        ("xch", "ble", "lb_ble_enable", "On only for the exchange"),
        ("xch", "ble", "lb_ble_connect", "Authenticated against the scanned fingerprint"),
        ("ble", "xch", "lb_xch_on_ble_rx", "Key and proof arrive"),
        ("xch", "crypto", "lb_crypto_verify", "Check the proof of key possession"),
        ("ui", "xch", "lb_xch_peer_uids", "HumanCheck screen: names and fingerprint"),
        ("ui", "xch", "lb_xch_set_confirmed", "met or ID checked; only confirmed names"),
        ("xch", "session", "lb_session_request", "Approval of the signing"),
        ("ui", "session", "lb_session_hold_complete", "Hold with a fingerprint"),
        ("xch", "openpgp", "lb_pgp_certify", "Certify the confirmed names"),
        ("xch", "ble", "lb_ble_send", "Return the certification"),
        ("xch", "storage", "lb_sys_write", "Met log"),
        ("xch", "ble", "lb_ble_disable", "Radio off again"),
    ]),
    dict(id="vault", title="Unlock and use the Vault", steps=[
        ("sdcard", "vault", "lb_vault_on_media", "Card detected"),
        ("vault", "ui", "lb_ui_on_media", "VaultPrompt"),
        ("ui", "session", "lb_session_request", "Unlock the media"),
        ("session", "fp", "lb_fp_match", "The fingerprint unlocks"),
        ("ui", "vault", "lb_vault_unlock", "Derive the volume key"),
        ("vault", "session", "lb_session_state", "Must be unlocked"),
        ("vault", "keystore", "lb_ks_get", "Volume key (wrapped, then unwrapped after the PIN)"),
        ("vault", "crypto", "lb_crypto_xts_init", "XTS context"),
        ("ui", "vault", "lb_vault_connect", "PTT hold connects"),
        ("vault", "usb", "lb_usb_msc_set_ready", "Drive appears on the host"),
        ("usb", "vault", "lb_vault_msc_read", "Host reads a block"),
        ("vault", "sdcard", "lb_sd_read", "Ciphertext block"),
        ("vault", "crypto", "lb_crypto_xts_crypt", "Decrypt, hand to the host"),
        ("ui", "vault", "lb_vault_lock", "Back, unplug or timeout"),
    ]),
    dict(id="backup", title="Back up and restore", steps=[
        ("ui", "backup", "lb_backup_create", "First use, or after a stale warning"),
        ("backup", "session", "lb_session_request", "Approval"),
        ("backup", "crypto", "lb_crypto_random", "Generate the recovery key"),
        ("backup", "keystore", "lb_ks_export_wrapped", "Wrapped secrets"),
        ("backup", "crypto", "lb_crypto_aead_seal", "Seal the file"),
        ("backup", "storage", "lb_sys_write", "System card"),
        ("ui", "qr", "lb_qr_encode", "Show the recovery key QR (once)"),
        ("ui", "qr", "lb_qr_decode", "Restore: scan the recovery key"),
        ("ui", "qrparse", "lb_qrparse", "RECOVERY_KEY type"),
        ("ui", "backup", "lb_backup_restore", "Confirm before overwriting"),
        ("backup", "storage", "lb_sys_read", "Read the file"),
        ("backup", "crypto", "lb_crypto_aead_open", "Authenticate and decrypt"),
        ("backup", "keystore", "lb_ks_import", "Restore"),
    ]),
]

OPEN_POINTS = [
    ("Event model", "Proposed, not yet approved: the UI never calls `crypto` or `keystore` directly, and every sensitive request goes through `session`. This map already follows that rule. It does not define a shared event queue."),
    ("Counter storage", "`lb_ks_attempt_begin` and `lb_ks_counter_advance` write before every check or code. They need a journalled, wear-levelled record that survives power cuts, with a stated write budget (verify flash endurance)."),
    ("Firmware update", "No component owns the update flow yet. `boot` has the slot calls, but something has to receive a signed image over USB or BLE and check it. Likely a small `update` component."),
    ("Host tool interface", "The v0 command-line tool (time sync, backup, update) needs a way to reach the device. The composite already uses 5 IN and 3 OUT endpoints, so a vendor interface may not fit. A custom CCID command set is the likely answer (decision needed)."),
    ("Core assignment", "Core 0 and Core 1 are stated for USB, crypto, keystore, Vault, UI, camera, fingerprint and BLE. `session`, `oath`, `xch` and `backup` are proposed here and unconfirmed."),
    ("Logging rule", "No secrets or PINs in logs; release builds log minimally. Not yet written into the architecture."),
    ("Security architecture", "That section has not been reviewed yet. Types such as `lb_level_t` and the keystore API may change when it is."),
    ("Repository layout", "The component list in the repository-layout block of LIBRA.md omitted `storage`, `vault` and `usb`. Fixed with this map."),
    ("Host simulation seam", "The UI and services are to be built on the host first, with simulated drivers behind the driver headers and the UI model kept separate from the renderer. The rendering toolkit (LVGL or hand-written) is undecided. See Host-side development in LIBRA.md."),
    ("Reused firmware", "If the pico-fido family is adopted, `openpgp`, `fido` and `oath` become thin adapters around it and their internals will differ from this sketch."),
]
